title: Houssem-Eddine Gueziri, Ph. D.
email: 
description: 
baseurl: "/Mekyll" # the subpath of your site, e.g. /blog
url: "http://ifedyukin.github.io" # the base hostname & protocol for your site
postCount: 5 # the number of posts on the "index" page

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

owner:
  name: Houssem-Eddine Gueziri
  bio: "Personal page."
  email: houssem.gueziri@mcgill.ca
  # Do not include the @ symbol in your Twitter username
  linkedin: houssemgueziri
  github: hgueziri
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: Houssem_Eddine_Gueziri
  google:
    analytics:
    verify:
    scholar: #id

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

collections:
  projects:
    output: true

