title: Houssem-Eddine Gueziri, Ph. D.
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hgueziri.github.io/" # the base hostname & protocol for your site
postCount: 5 # the number of posts on the "index" page

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

owner:
  name: Houssem-Eddine Gueziri
  bio: ""
  email: houssem.gueziri@mcgill.ca
  # Do not include the @ symbol in your Twitter username
  linkedin: houssemgueziri
  github: hgueziri
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: Houssem_Eddine_Gueziri
  google:
    analytics:
    verify:
    scholar: #id


collections:
  projects:
    output: true

